### ISSUE TITLE
Could you add python-mysqldb 

### ISSUE THREAD

**Issue by jean-jcrx** [bianjp/docker-mariadb-alpine#3]
Any possibility you could add this? I think with
apk install python-mysqldb

**Comment by jean-jcrx** [comment]
Here is the command to add: 
apk --update add python py-mysqldb.

**Comment by bianjp** [comment]
Great to hear that it helps someone. I'll add it later today.
I'll also take some time to sync the entrypoint script with official mariadb docker image, as this repo hasn't been updated for a long time.

**Comment by bianjp** [comment]
Sorry, I finally decided that adding `py-mysqldb` is probably not appropriate for an lightweight container (otherwise it will pull in a lot dependencies).

You may create a new docker image based on this one, though.

**Comment by jean-jcrx** [comment]
Thank you, understood.
