### ISSUE TITLE
Unknown database ?

### ISSUE THREAD

**Issue by vschiavoni** [bianjp/docker-mariadb-alpine#4]
I try to instantiate it like this:

`docker run --name mariadb-native -e MYSQL_USER="admin" -e MYSQL_PASSWORD="admin" -e MYSQL_ROOT_PASSWORD="admin" -e MYSQL_DATABASE="mariadb-test" -d bianjp/mariadb-alpine:latest`

As the image boots, `docker logs mariadb-native` shows this:

`Database initialized
180416 22:03:41 mysqld_safe Logging to '/var/lib/mysql/2105ae517565.err'.
180416 22:03:41 mysqld_safe Starting mysqld daemon with databases from /var/lib/mysql
MySQL init process in progress...
ERROR 1049 (42000): Unknown database '"mariadb-test"'`

**Comment by bianjp** [comment]
It's quite strange that `mysql database_name -e "CREATE USER username"` will report "Unknown database" error, even the database has already been created.
Anyway, it should be fixed now.
