### ISSUE TITLE
Support for additional my.cnf conf file ?

### ISSUE THREAD

**Issue by vschiavoni** [bianjp/docker-mariadb-alpine#5]
Is there support to specify an additional my.cnf file that is used to customized/override the default one?
I've tried with:

`docker run --name mariadb-native -v /home/ubuntu/custom:/etc/mysql/conf.d ...
`
where inside custom/custom-file.cnf there is:

```
[mysqld]
innodb_buffer_pool_size=64M
```

Is this supported ?

**Comment by bianjp** [comment]
This is currently not supported as `/etc/mysql/my.cnf` in Alpine MariaDB package does not contain `!includedir /etc/mysql/conf.d/`.
I'll fix it in a few minutes.
