### ISSUE TITLE
mariadb version

### ISSUE THREAD

**Issue by Erwane** [bianjp/docker-mariadb-alpine#6]
Hi,

Your documentation announce the latest mariadb as 10.2 (from alpine package) but it's 10.1 in your container.

Could you update please ?

```
$ docker-compose exec mysql mysql -V
mysql  Ver 15.1 Distrib 10.1.32-MariaDB, for Linux (x86_64) using readline 5.1
```

**Comment by Erwane** [comment]
Oops ... it's in "edge" alpine :(
Sorry

**Comment by bianjp** [comment]
I just added a description about versions in README.
