### ISSUE TITLE
Create release tags for images

### ISSUE THREAD

**Issue by miramir** [bianjp/docker-mariadb-alpine#8]
Please create release tags for images for greater build repeatability.

**Comment by bianjp** [comment]
For the ease of maintenance, this docker image is built from prebuilt mariadb package provided by alpine,  so it's not easy to tag the MariaDB version.

And I don't want to bother to maintain multiple branches or tags. This is just a simple and __working__ image which should only be used in development and test. It's better to use official MariaDB image for production environments.

**Comment by miramir** [comment]
ну ок
